Fix SCHEDULING-141 . Exception message can be null. Specify message for NoClassDefFoundError.
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/proactive/scheduling/trunk@10586 28e8926c-6b08-0410-baaa-805c5e19b8d6