SCHEDULING-1486: Added the possibility to execute selection script from RM CLI
Added to ResourceManager interface: public <T> List<ScriptResult<T>> executeScript(Script<T> script, String targetType, Set<String> targets) method to execute scripts remotely on specified targets

Added to RM-CLI: execRemote(scriptFilePath, targetType, targets)     Execute the content of the given script file on specified targets, targetType can be on of [NODESOURCE_NAME, NODE_URL, HOSTNAME]

For example if there is no nodes in RM:
 > execRemote("H:\\schedulingTrunk\\samples\\scripts\\selection\\select.js",'NODESOURCE_NAME',"Default");
Script select.js targets: [Default]
No scripts were executed, maybe no targets found or no registered nodes at all

2 nodes added:
 > execRemote("H:\\schedulingTrunk\\samples\\scripts\\selection\\select.js",'NODESOURCE_NAME',"Default");
Script select.js targets: [Default]
Script result: false, output:
Script result: false, output:

For example when adding print("Added output"); into the select.js script it is visible:
 > execRemote("H:\\schedulingTrunk\\samples\\scripts\\selection\\select.js",'NODESOURCE_NAME',"Default");
Script select.js targets: [Default]
Script result: false, output:
Added output

Script result: false, output:
Added output

For example, if the target type is HOSTNAME then the script is executed on a single node of that host:
 > execRemote("H:\\schedulingTrunk\\samples\\scripts\\selection\\select.js",'HOSTNAME',"optimus.activeeon.com");
Script select.js targets: [optimus.activeeon.com]
Script result: false, output:
Added output

For example, if an exception occured it is visible:
 > execRemote("H:\\schedulingTrunk\\samples\\scripts\\selection\\checkPhysicalFreeMem.js",'NODESOURCE_NAME',"Default");
Script checkPhysicalFreeMem.js targets: [Default]
An exception occured when running script: : An exception occured while executing the script
Display stack trace ? (yes/no) >
Script result: null
An exception occured when running script: : An exception occured while executing the script
Display stack trace ? (yes/no) > yes
java.lang.Exception: An exception occured while executing the script
        at org.ow2.proactive.scripting.Script.execute(Script.java:292)
        at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:399)
        at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:257)
        at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:201)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:626)
        at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:587)
        at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:949)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:180)
        at org.objectweb.proactive.Service.blockingServeOldest(Service.java:155)
        at org.objectweb.proactive.Service.fifoServing(Service.java:131)
        at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:323)
        at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:203)
        at java.lang.Thread.run(Thread.java:662)
Caused by: javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: ReferenceError: "arguments" n'est pas dÚfini (<Unknown source>#13) in <Unknown source> at line number 13
        at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:110)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:232)
        at org.ow2.proactive.scripting.Script.execute(Script.java:283)
        ... 17 more
Script result: null

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/proactive/scheduling/trunk@21547 28e8926c-6b08-0410-baaa-805c5e19b8d6