SCHEDULING-2033 Switch to jline2 api in rest-cli
jline2 is used in native cli; jline1 brought by rest-cli to dist/lib
creates conflicts:

  java.lang.IncompatibleClassChangeError: Found class jline.Terminal, but interface was expected

Switch to jline2 along the same lines as in
5f6221da69f9bfda4407c3ae50410cc1f8aa1991.

Change-Id: I2280021dc23b652a7b540645e24bbe9ce5c5da28